#!/bin/sh

### BEGIN INIT INFO
# Provides:          ADdroneServer
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ADdrone server
# Description:       controler for ADdrone
### END INIT INFO

# Change the next 3 lines to suit where you install your script and what you want to call it
DIR=/home/dawid/git/ADdroneServer
DAEMON=$DIR/ADdroneServer.py
DAEMON_NAME=ADdroneServer

# Add any command line options for your daemon here
DAEMON_OPTS="-p 6666 -d $DIR"

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    log_daemon_msg "($DAEMON)"
    if [ ! -e $DAEMON ]; then
      echo "Cannot work with ADdrone. main script is missing!"
      exit 1
    fi

    start-stop-daemon \
      --start \
      --background \
      --pidfile $PIDFILE \
      --make-pidfile \
      --user $DAEMON_USER \
      --chuid $DAEMON_USER \
      --startas $DAEMON \
      -- $DAEMON_OPTS
    ret=$?
    if [ $ret -eq 0 ]; then
      echo "OK!"
    fi
    log_end_msg $ret
}

do_run () {
    log_daemon_msg "Runing ($DAEMON)"
    if [ ! -e $DAEMON ]; then
      echo "Cannot work with ADdrone. main script is missing!"
      exit 1
    fi

    start-stop-daemon \
      --start \
      --pidfile $PIDFILE \
      --make-pidfile \
      --user $DAEMON_USER \
      --chuid $DAEMON_USER \
      --startas $DAEMON \
      -- $DAEMON_OPTS
    ret=$?
    if [ $ret -eq 0 ]; then
      echo "OK!"
    fi
    log_end_msg $ret
}

do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}


case "$1" in

    start)
        do_start
        ;;
    run)
        do_run
        ;;

    stop)
        do_stop
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
